const { infoEmbed } = require("../utilities/embeds");

module.exports = {
	name: "pong",
	description: ":)",
	botPermissions: ["EMBED_LINKS"],
	async execute(message, args) {
		message.channel.send(infoEmbed("***Pong*** is a [table tennis](https://en.wikipedia.org/wiki/Table_tennis)–themed [arcade video game](https://en.wikipedia.org/wiki/Arcade_game#Arcade_video_games), featuring simple two-dimensional graphics, manufactured by [Atari](https://en.wikipedia.org/wiki/Atari,_Inc) and originally released in 1972. It was one of the earliest arcade video games; it was created by [Allan Alcorn](https://en.wikipedia.org/wiki/Allan_Alcorn) as a training exercise assigned to him by Atari co-founder [Nolan Bushnell](https://en.wikipedia.org/wiki/Nolan_Bushnell), but Bushnell and Atari co-founder [Ted Dabney](https://en.wikipedia.org/wiki/Ted_Dabney) were surprised by the quality of Alcorn's work and decided to manufacture the game. Bushnell based the game's concept on an electronic ping-pong game included in the [Magnavox Odyssey](https://en.wikipedia.org/wiki/Magnavox_Odyssey), the first [home video game console](https://en.wikipedia.org/wiki/Home_video_game_console). In response, Magnavox later sued Atari for patent infringement. \n\n*Pong* was the first commercially successful video game, and it helped to establish the [video game industry](https://en.wikipedia.org/wiki/Video_game_industry) along with the Magnavox Odyssey. Soon after its release, several companies began producing games that closely mimicked its gameplay. Eventually, Atari's competitors released new types of video games that deviated from *Pong*'s original format to varying degrees, and this, in turn, led Atari to encourage its staff to move beyond *Pong* and produce more innovative games themselves. \n\nAtari released several sequels to *Pong* that built upon the original's gameplay by adding new features. During the 1975 Christmas season, Atari released a home version of *Pong* exclusively through [Sears](https://en.wikipedia.org/wiki/Sears,_Roebuck_and_Company) retail stores. The home version was also a commercial success and led to numerous clones. The game was remade on numerous home and portable platforms following its release. *Pong* is part of the permanent collection of the [Smithsonian Institution](https://en.wikipedia.org/wiki/Smithsonian_Institution) in Washington, D.C., due to its cultural impact. \n\n\nFor more info, go to https://en.wikipedia.org/wiki/Pong"));
	},
};
